export const pages = {
    1: 'Welcome to the life of Tim! A middle aged accountant from Syracuse, New York. The life is Tim’s but the choices are yours. Will Tim be ordinary? Or will he break the mold and be extraordinary? Only you can decide.',
    2: '9 minutes goes by, and once again BEEP! BEEP! BEEP! Do you snooze again? Or get up',
    3: 'You got your wish. You finally get to sleep all you want. In fact all you get to do is sleep. You had a brain aneurysm and died. So concludes the life of Tim.',
    4: " Oh! You are a real go getter, aren’t you? Tim arrives at work exactly on time, just like he does every day. His boss Hank is sure to notice What is this? He did notice.Hank gives you the new account, Braxton, a large tech company that was just valued for a billion dollars.He tells you that if you do well with this one you are a shoe in for a promotion. Excited for the opportunity you quickly begin to carefully look over the account and you notice an anomaly.Each month 50 thousand dollars is making its way into an account called Tregor & Parson, but there is no record of Braxton receiving any services from them. You call Braxton and ask for their CFO and explain who you are.The Braxton CFO is a man named Larry Perry, an unfortunate name.Larry goes quiet when you explain what you have found, then he says, I will tell you what.Tim you can fix it so that no one else finds this issue again and we will cut you ten grand a month.Or you can report us and see where that finds you.What do you do?",
    5: "You slept in for nine minutes and are thus, nine minutes late. If you had not slept in you would have been right on time. But we cannot fix that now, can we? Your boss Hank is furious, and says you are on thin ice, even though this is the first time you have been late ever. He tells you he was going to give you a new account, but now he is giving it to Kimberly, your arch nemesis, who you have hated since she stole your date, Liz, at the corporate Christmas party in 2005. And Kim is not even a good accountant. She made a mistake on her last account that got them audited by the IRS.",
    6: "You do exactly that. You do not say anything. A week goes by and you suddenly get a phone call from an anonymous number. It tells you to look in the back seat of your car after work. And sure enough there is ten grand just as promised. That is almost twice what you make in a month. What are you going to do with this new found wealth? This makes you very upset.What are you going to do? ",
    7: 'You report  Braxton to the authorities immediately. Hank is slightly upset at the thought of losing such a large account, but he understands. You are just doing your job. Later that night you see that a raid has been conducted at Braxton and Larry has been arrested.You smile to yourself as you eat your meal of steamed vegetables. The next day you get up and go to work exactly on time, as always.As you come in you hear whispering.Hank is retiring and there is a chance that one of you will be promoted to manager.Do you want this promotion ?',
    8: "You scream at Hank and he takes a couple steps back. He has never heard your voice raise, let alone seen you angry. You really tear into him.You bring up how much you have done for the company, how you have never been late, all of Kimberly’s mistakes. Hank straightens himself out and says, that you should have thought of the consequences when you decided to sleep in. Now you are furious and go for the jugular.You tell Hank he should have thought of the consequences when he decided to be such a miserable ass and caused his wife to leave him.He knew Hank still kept a picture of her on his desk. Hank begins to cry, wipes his tears on his sleeve, and tells you to go collect your things.You are fired. Tim always kept his cubicle nice so it is not hard to pack.Kimberly peeks her head over her cubicle and gives you the finger. You walk out with your stuff and decide that you’ll go for a walk by Onondaga Lake.To get there you need to cross a busy intersection but it does not look like any cars are coming.",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
    25: "",
    26: "",
    27: "",
    28: "",
    29: "",
    30: "",
    31: "",
    32: "",
    33: "",
    34: "",
    35: "",
    36: "",
    37: "",
    38: "",
    39: "",
    40: "",
    41: "",
    42: "",
    43: "",
    44: "",
    45: "",
    46: "",
    47: "",
    48: "",
    49: "",
    50: "",
    51: "",
    52: "",
    53: "",
    54: "",
    55: "",
    56: "",

};


export const choices = {
    1: [{'yes': 2}, {'no': 3}],
    2: [{'nope':4}, {'yup':5}],
    3:[],
    4:[],
    5:[],
    6:[],
    7:[],
    8:[],
    9:[],
    10:[],
    11:[],
    12:[],
    13:[],
    14:[],
    15:[],
    16:[],
    17:[],
    18:[],
    19:[],
    20:[],
    21:[],
    22:[],
    23:[],
    24:[],
    25:[],
    26:[],
    27:[],
    28:[],
    29:[],
    30:[],
    31:[],
    32:[],
    33:[],
    34:[],
    35:[],
    36:[],
    37:[],
    38:[],
    39:[],
    40:[],
    41:[],
    42:[],
    43:[],
    44:[],
    45:[],
    46:[],
    47:[],
    48:[],
    49:[],
    50:[],
    51:[],
    52:[],
    53:[],
    54:[],
    55:[],
    56:[],
};