export const pages = {
    1: 'Welcome to the life of Tim! A middle aged accountant from Syracuse, New York. The life is Tim’s but the choices are yours. Will Tim be ordinary? Or will he break the mold and be extraordinary? Only you can decide.',
    2: '9 minutes goes by, and once again BEEP! BEEP! BEEP! Do you snooze again? Or get up',
    3: 'You got your wish. You finally get to sleep all you want. In fact all you get to do is sleep. You had a brain aneurysm and died. So concludes the life of Tim.',
    4: " Oh! You are a real go getter, aren’t you? Tim arrives at work exactly on time, just like he does every day. His boss Hank is sure to notice What is this? He did notice.Hank gives you the new account, Braxton, a large tech company that was just valued for a billion dollars.He tells you that if you do well with this one you are a shoe in for a promotion. Excited for the opportunity you quickly begin to carefully look over the account and you notice an anomaly.Each month 50 thousand dollars is making its way into an account called Tregor & Parson, but there is no record of Braxton receiving any services from them. You call Braxton and ask for their CFO and explain who you are.The Braxton CFO is a man named Larry Perry, an unfortunate name.Larry goes quiet when you explain what you have found, then he says, I will tell you what.Tim you can fix it so that no one else finds this issue again and we will cut you ten grand a month.Or you can report us and see where that finds you.What do you do?",
    5: "You slept in for nine minutes and are thus, nine minutes late. If you had not slept in you would have been right on time. But we cannot fix that now, can we? Your boss Hank is furious, and says you are on thin ice, even though this is the first time you have been late ever. He tells you he was going to give you a new account, but now he is giving it to Kimberly, your arch nemesis, who you have hated since she stole your date, Liz, at the corporate Christmas party in 2005. And Kim is not even a good accountant. She made a mistake on her last account that got them audited by the IRS.",
    6: "You do exactly that. You do not say anything. A week goes by and you suddenly get a phone call from an anonymous number. It tells you to look in the back seat of your car after work. And sure enough there is ten grand just as promised. That is almost twice what you make in a month. What are you going to do with this new found wealth? This makes you very upset.What are you going to do? ",
    7: 'You report  Braxton to the authorities immediately. Hank is slightly upset at the thought of losing such a large account, but he understands. You are just doing your job. Later that night you see that a raid has been conducted at Braxton and Larry has been arrested.You smile to yourself as you eat your meal of steamed vegetables. The next day you get up and go to work exactly on time, as always.As you come in you hear whispering.Hank is retiring and there is a chance that one of you will be promoted to manager.Do you want this promotion ?',
    8: "You scream at Hank and he takes a couple steps back. He has never heard your voice raise, let alone seen you angry. You really tear into him.You bring up how much you have done for the company, how you have never been late, all of Kimberly’s mistakes. Hank straightens himself out and says, that you should have thought of the consequences when you decided to sleep in. Now you are furious and go for the jugular.You tell Hank he should have thought of the consequences when he decided to be such a miserable ass and caused his wife to leave him.He knew Hank still kept a picture of her on his desk. Hank begins to cry, wipes his tears on his sleeve, and tells you to go collect your things.You are fired. Tim always kept his cubicle nice so it is not hard to pack.Kimberly peeks her head over her cubicle and gives you the finger. You walk out with your stuff and decide that you’ll go for a walk by Onondaga Lake.To get there you need to cross a busy intersection but it does not look like any cars are coming.",
    9: "You head off to your cubicle and begin to work on a cash flow. As you are crunching away at the numbers you hear Kimberly excitedly talking to someone from Braxton. After she hangs up the phone she cheers loudly that she is going to be rich. You start to fume.You hate Kimberly.It could have been you getting rich.Wait, how is she getting rich? You do not make any more money from getting a new account.A new account is just a stepping stone to a promotion if you handle it well.So how is she making money? What do you do?",
    10: "You wait and when the walk sign lights up, you cross safely. As you walk along the lake you notice something in the water. It is shiny and gold. You step into the water even though you are fully clothed and pick it up. It is a lamp just like the one Alladin found in Arabian Nights. Do you rub it? Or try to sell it?",
    11: "When you are halfway across a Nissan Sentra comes flying down the road, and plows into you. It does not even stop. Tim flips clear over the car and is dead before he hit the ground. So concludes the life of Tim.",
    12: "Tim knows exactly how he is going to invest. He had been making hypothetical stock portfolios on Yahoo Finance for years. In just a month he has turned 10 grand into 100 grand. And that is not even counting the other 10 grand he received from Braxton in that time. He reinvests all of it and soon he has over a million dollars. You can easily retire if you want. What do you do?",
    13: "Boy oh boy do you buy something nice. Really nice in fact. You buy some shoes for your grandma who is super old. But she does like the shoes and says they are real nice. You also get one of those little bird statues that bobs and drinks water for your desk. Oh and Tim also buys a corvette.He pays all $9900 of the down payment in cash.Tim loves the car and shoes it off to everyone.Kimberly is jealous and knows she makes more money than you.So how did you afford the car she wonders. Her brother, Geoff works for the IRS and she convinces him to look into your affairs.After seeing that you bought a car with money that came from nowhere, they decide to audit you. You did not keep the receipt for the shoes, the bird, or the car, or really any receipts in general.So you are pretty screwed. They charge you with tax evasion, but they still want to know where you got the money.They offer you a deal for less time if you tell them.Do you?",
    14: "You pay off your debts. Smart. Because you did not do anything flashy, so no one is going to notice. Plus banks just want their money back. They do not really care where it comes from do they? You fly right under the radar.To everyone it just seems like you are a normal accountant.They have no idea that you are making an extra $120, 000 a year tax free. Then you think about it again.Sure the banks probably won’t notice you paying off debts, but the IRS will.Especially if it becomes a pattern.So now you really have to get creative.You can either just use the money to pay for little things and never put it in a bank, or figure out a way to launder it.Which will you do?",
    15: "You announce your retirement. Everyone is shocked. You can not have possibly collected enough in your 401K or your ROTH IRA. None the less you collect your sheet cake that Hank reluctantly provided and scurry on out of that place for ever. Where will you go to spend your retirement?",
    16: "Holy cow! You are making so much money!!! Every stock you invest in just keeps going up. Tim now has millions of dollars. However you have been paying more attention to your stocks than to the Braxton account.Tim forgets to move some money between accounts.He tunes into the news that night and sees that Larry, the Braxton CFO is being arrested for embezzlement, and that the Feds are looking for anyone with more information.Do you?",
    17: "Tim spends the rest of his time in Syracuse just like he wanted. He plays poker on Tuesdays, Darts on Wednesdays, and on Thursdays he takes his cat, Mimsy, to the groomers. He does that for another 25 years coasting on his investments, and dies quietly in his sleep. So completes the life of Tim.",
    18: "Tim heads off to Fiji where he meets a gorgeous woman named Susan. She also worked as an accountant and decided to retire to Fiji. After dating for a short while they move in together and get married. Tim’s cat, Mimsy, is his best man, which Susan thinks is endearing. They spend the rest of their lives together. So concludes the life of Tim.",
    19: "Tim heads to Sedona. You have been doing some reading and get really into crystals. There supposed to be a pretty large energy vortex there, to get your crystals charged. After asking around a local tells you that a woman down the street charges crystals and aligns chakras. Tim opens the door and finds none other than Liz, the date that Kimberly stole.She does not recognize you at first but after you go to pay for the crystal charging, and open your wallet she sees the old business card you have, and realizes who you are. She apologizes and admits that she was really after Kimberly the whole time.She just used you to get closer to her, and that that was wrong of her to do to you.You forgive her, and she invites you to stay with her and her friends. Her friends turn out to be involved in a cult.After a few months of hanging out with them you abandon your life as Tim and become brother husband 3, that is your name brother husband 3, to a woman named Francine.Liz is also married to Francine but not to you.So concludes the life of Tim.",
    20: "You go into the office, and as you round into your cubicle a man is sitting in your chair. He turns around and introduces himself as Special Agent Schwartz of the FBI. Another agent steps behind you and puts you in hand cuffs. Her name is Special Agent Weiss. They tell you that you are being arrested for money laundering and tax fraud.They offer you a deal if you testify against Larry.Do you take the deal?",
    21: "You call in sick and Hank is super weird about it. He is oddly instant that you come in. Then he asks if you are going to be home all day. You tell him of course you are. You are supposed to be sick after all. Do you stay home or flee?",
    22: "You take the deal and testify in exchange for half the time in prison. As you are giving your testimony you see Larry mouth something to you. It looks a lot like you are a dead man. But maybe you are mistaken? On your first day of federal penitentiary you are introduced to your two cell mates, Curly and Moe.They seem like nice guys. Lights go out at 8 pm.And at 8: 10 Curly and Moe turn out not to be so nice.Moe holds you down while Curly holds a pillow over your face.He says, condolences from Larry.You kick and squirm but ultimately stop breathing.So ends the life of Tim.",
    23: "",
    24: "",
    25: "",
    26: "",
    27: "",
    28: "",
    29: "",
    30: "",
    31: "",
    32: "",
    33: "",
    34: "",
    35: "",
    36: "",
    37: "",
    38: "",
    39: "",
    40: "",
    41: "",
    42: "",
    43: "",
    44: "",
    45: "",
    46: "",
    47: "",
    48: "",
    49: "",
    50: "",
    51: "",
    52: "",
    53: "",
    54: "",
    55: "",
    56: "",

};


export const choices = {
    1: [{'yes': 2}, {'no': 3}],
    2: [{'nope':4}, {'yup':5}],
    3:[],
    4:[],
    5:[],
    6:[],
    7:[],
    8:[],
    9:[],
    10:[],
    11:[],
    12:[],
    13:[],
    14:[],
    15:[],
    16:[],
    17:[],
    18:[],
    19:[],
    20:[],
    21:[],
    22:[],
    23:[],
    24:[],
    25:[],
    26:[],
    27:[],
    28:[],
    29:[],
    30:[],
    31:[],
    32:[],
    33:[],
    34:[],
    35:[],
    36:[],
    37:[],
    38:[],
    39:[],
    40:[],
    41:[],
    42:[],
    43:[],
    44:[],
    45:[],
    46:[],
    47:[],
    48:[],
    49:[],
    50:[],
    51:[],
    52:[],
    53:[],
    54:[],
    55:[],
    56:[],
};